// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJlPLX4DfVO_A4b8-gcTvNxeptkC9cpi8',
    appId: '1:311505412696:ios:bc8e7b7f969e0d72fe202d',
    messagingSenderId: '311505412696',
    projectId: 'cybersecurity-pulse-9841d',
    storageBucket: 'cybersecurity-pulse-9841d.firebasestorage.app',
    androidClientId: '311505412696-tagg8th8mvl65uh5s82h3g4gvdpdmumc.apps.googleusercontent.com',
    iosClientId: '311505412696-n7mostm4cr7p9kgbvr36p7an3h3rfiaj.apps.googleusercontent.com',
    iosBundleId: 'com.example.cyberpulseAcademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJlPLX4DfVO_A4b8-gcTvNxeptkC9cpi8',
    appId: '1:311505412696:ios:bc8e7b7f969e0d72fe202d',
    messagingSenderId: '311505412696',
    projectId: 'cybersecurity-pulse-9841d',
    storageBucket: 'cybersecurity-pulse-9841d.firebasestorage.app',
    androidClientId: '311505412696-tagg8th8mvl65uh5s82h3g4gvdpdmumc.apps.googleusercontent.com',
    iosClientId: '311505412696-n7mostm4cr7p9kgbvr36p7an3h3rfiaj.apps.googleusercontent.com',
    iosBundleId: 'com.example.cyberpulseAcademy',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkWgSiR5otA5WVXADYSXqkWkuCGqDMq9M',
    appId: '1:311505412696:web:b2748a15214b601cfe202d',
    messagingSenderId: '311505412696',
    projectId: 'cybersecurity-pulse-9841d',
    authDomain: 'cybersecurity-pulse-9841d.firebaseapp.com',
    storageBucket: 'cybersecurity-pulse-9841d.firebasestorage.app',
    measurementId: 'G-66VZDJYT5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzWg5jGEFbOw863S89E2SyZO6TJdpZ8-I',
    appId: '1:311505412696:android:c027bb25db0b49d7fe202d',
    messagingSenderId: '311505412696',
    projectId: 'cybersecurity-pulse-9841d',
    storageBucket: 'cybersecurity-pulse-9841d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkWgSiR5otA5WVXADYSXqkWkuCGqDMq9M',
    appId: '1:311505412696:web:1098452d9b0769b0fe202d',
    messagingSenderId: '311505412696',
    projectId: 'cybersecurity-pulse-9841d',
    authDomain: 'cybersecurity-pulse-9841d.firebaseapp.com',
    storageBucket: 'cybersecurity-pulse-9841d.firebasestorage.app',
    measurementId: 'G-CHY7Y38DLG',
  );
}
